### PR TITLE
Fix issue w/ python 3, add support for newer versions of python.

### PR DESCRIPTION
**Pull request by asherf**
```

Traceback (most recent call last):
  File "setup.py", line 41, in <module>
    "License :: OSI Approved :: Apache Software License",
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/setuptools/__init__.py", line 143, in setup
    return distutils.core.setup(**attrs)
  File "/opt/python/3.5.6/lib/python3.5/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/opt/python/3.5.6/lib/python3.5/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/opt/python/3.5.6/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/setuptools/command/test.py", line 228, in run
    self.run_tests()
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/setuptools/command/test.py", line 250, in run_tests
    exit=False,
  File "/opt/python/3.5.6/lib/python3.5/unittest/main.py", line 94, in __init__
    self.parseArgs(argv)
  File "/opt/python/3.5.6/lib/python3.5/unittest/main.py", line 141, in parseArgs
    self.createTests()
  File "/opt/python/3.5.6/lib/python3.5/unittest/main.py", line 148, in createTests
    self.module)
  File "/opt/python/3.5.6/lib/python3.5/unittest/loader.py", line 219, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/opt/python/3.5.6/lib/python3.5/unittest/loader.py", line 219, in <listcomp>
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/opt/python/3.5.6/lib/python3.5/unittest/loader.py", line 153, in loadTestsFromName
    module = __import__(module_name)
  File "/home/travis/build/korfuri/django-prometheus/django_prometheus/__init__.py", line 15, in <module>
    import pip_prometheus
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/pip_prometheus/__init__.py", line 29, in <module>
    LoadInstallations(_installed_apps)
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/pip_prometheus/__init__.py", line 17, in LoadInstallations
    installations = json.loads(output)
  File "/opt/python/3.5.6/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
```

https://travis-ci.org/korfuri/django-prometheus/jobs/545338320

### CODE REVIEW

**Comment by asherf** [comment]
@korfuri FYI.

**Comment by asherf** [comment]
@korfuri any chance you can find time to merge this and publish a new version ?
thanks!

**Comment by asherf** [comment]
@korfuri friendly ping... can we get this in and published ? 
Thank you

**Comment by korfuri** [comment]
Thanks for the contrib and sorry for the delay!

**Comment by korfuri** [comment]
Thanks! 1.2.0 has just been released.

**Pull request merged**
